### ISSUE TITLE
Add an own page for statistics 

### ISSUE THREAD

**Issue by blackus3r** [blackus3r/post-worktime-logger#21]
This could contain a chart.

**Comment by selamanse** [comment]
I'd like to give it a shot :)

**Comment by blackus3r** [comment]
@selamanse yeah, if you want to do that, feel free :)

**Comment by blackus3r** [comment]
I think, a bar graph (Top 25) would be nice. 

Maybe a grid would also be nice? And a column with total worktime of all posts.

**Comment by selamanse** [comment]
ok... I tried getting the data with wpquery (sort on meta data) and display a simple horizontal bar chart with chart.js #25 

I didn't know where to put the page so it is placed as a submenu item in "Plugins" menu.

**Comment by selamanse** [comment]
this is what it looks like:

![screen shot 2016-10-23 at 02 56 25](https://cloud.githubusercontent.com/assets/3129224/19623580/3d24a11c-98ce-11e6-93b2-72788ed23d2a.png)

**Comment by blackus3r** [comment]
Nice :) 
Is it possible to make the bars a bit smaller and calculating the hours instead of the seconds? 
If you are ready, you can make a pull request. 

I have done the first steps for an own settings page etc.  in another branch. So I will do it with the menu.

**Comment by selamanse** [comment]
Sorry wasn't able to to this the last few days. :-/ is there anything left? I think I can work on it this weekend.

**Comment by blackus3r** [comment]
No Problem. :-) 
I don't know, but if you find something to do, feel free. 
I will merge the fixed branch into swimlane/1.3.0 so you can work in this branch with the latest version, which contains the settings page and your statistics page.

**Comment by blackus3r** [comment]
I will close this issue, when the pull request is merged, so if you want to do something, please open a new issue for that.
