### ISSUE TITLE
Implement "auto start" checkbox in options page 

### ISSUE THREAD

**Issue by blackus3r** [blackus3r/post-worktime-logger#33]
This should be a checkbox in the settings page like this 
- [ ] Disable autostart (Acttivate this, to prevent the time from starting automatically on post editing)

**Comment by zachwills** [comment]
I can knock this one out too.

**Comment by blackus3r** [comment]
Feel free :)

**Comment by mazzcris** [comment]
Is @zachwills working on this? I can do it if needed

**Comment by zachwills** [comment]
Hey @mazzcris I was going to do it in the morning

**Comment by blackus3r** [comment]
I want to release v1.3.0.

So you should checkout swimlane/1.4.0

**Comment by zachwills** [comment]
@blackus3r alright will do the PR against that branch

**Comment by zachwills** [comment]
@blackus3r can you merge 1.3 into this one? right now it doesnt have the settings page.

**Comment by zachwills** [comment]
@blackus3r nevermind I just rebased master into it
