### ISSUE TITLE
Implement a option to set the maximum time of absence till the counter pause

### ISSUE THREAD

**Issue by blackus3r** [blackus3r/post-worktime-logger#34]
At the moment, this is hardcoded.

**Comment by zachwills** [comment]
I'll work on adding this :)

**Comment by blackus3r** [comment]
Thanks, please make a pull request into swimlane/1.3.0 when you are ready. 

You should checkout this swimlane branche to get the version, which has already implemented the options page. You only have to add a textfield for setting up the max value :)

**Comment by zachwills** [comment]
@blackus3r woops I didn't realize that! I started adding the options page against master 😛 

I'll check out that branch!

**Comment by blackus3r** [comment]
Sorry, I should have added a notice in the issue description for that. 
I hope that you didn't have much work until now.
