### ISSUE TITLE
Consider conforming to the WordPress Coding Standards

### ISSUE THREAD

**Issue by zachwills** [blackus3r/post-worktime-logger#38]
Since this is a WordPress plugin it might make sense to conform to the [WPCS](https://codex.wordpress.org/WordPress_Coding_Standards).

You can add PHPCS and PHPCBF integration so you can run reports to see what lines aren't matching the standard, and PHPCBF will automatically fix some of the issues found (the ones that can be fixed).

**Comment by blackus3r** [comment]
This would be nice, I will have a look at it :-)

**Comment by blackus3r** [comment]
Are you familiar with that? Can you show me, how to do that?

**Comment by zachwills** [comment]
Yeah I am familiar. I can integrate it with the project in a new PR if you'd like.

**Comment by blackus3r** [comment]
That would be nice.

**Comment by zachwills** [comment]
Can you add the `hacktoberfest` and `in progress` label to this?

**Comment by zachwills** [comment]
@blackus3r which branch should this PR go against?

**Comment by blackus3r** [comment]
Master
