### ISSUE TITLE
Add link in readme files

### ISSUE THREAD

**Issue by blackus3r** [blackus3r/post-worktime-logger#49]
I think it is a good idea, to link to my blogs series of post worktime logger like this:

German changelog and tutorials of ths plugin can be found on [DerPade](http://www.derpade.de/series/post-worktime-logger/)

**Comment by ilimugur** [comment]
I'd like to get this out of your way if you'd like.

**Comment by blackus3r** [comment]
@ilimugur Sorry, there is already a pull request for that, see: https://github.com/blackus3r/post-worktime-logger/pull/53

**Comment by ilimugur** [comment]
No problems.
