### ISSUE TITLE
Add paypal donate link 

### ISSUE THREAD

**Issue by blackus3r** [blackus3r/post-worktime-logger#50]
Add donate link to readme files. 

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=28WZAXQDXYZ5A

**Comment by dhruv007patel** [comment]
Up for this.

**Comment by blackus3r** [comment]
Thanks.

**Comment by blackus3r** [comment]
Sorry, I have seen that there is already a pull request for this. see: https://github.com/blackus3r/post-worktime-logger/pull/51
