### ISSUE TITLE
Show total amount of worktime of all posts on statistics page

### ISSUE THREAD

**Issue by blackus3r** [blackus3r/post-worktime-logger#56]

**Comment by mazzcris** [comment]
@blackus3r something like "total worktime: hh:mm:ss" just under "statistics"?

**Comment by mazzcris** [comment]
Proposal:
<img width="531" alt="total worktime" src="https://cloud.githubusercontent.com/assets/6614577/19785477/c9ef631a-9c99-11e6-90c2-7ce123d3ac11.png">

**Comment by mazzcris** [comment]
#60

**Comment by mazzcris** [comment]
See #60
