### ISSUE TITLE
Improve statistics page

### ISSUE THREAD

**Issue by blackus3r** [blackus3r/post-worktime-logger#62]
Implement a number input field to change the number of posts shown in the statistics page. 

Please use an input of type number, like this: 

`<input type="number" name="numberOfPosts" min="1" max="250">`

Also check in backend, if we got a valid value!!!

Dont forget:
- checkout swimlane/1.4.0 for this feature
- make a pullrequest into swimlane/1.4.0
- Reference this issue
- Comment on this issue, if you are working on it.

**Comment by selamanse** [comment]
will try my luck on this again :)

**Comment by blackus3r** [comment]
Thanks 👍

**Comment by selamanse** [comment]
just sent out PR #65
