### ISSUE TITLE
Add dev setup info and dockerfile

### ISSUE THREAD

**Issue by selamanse** [blackus3r/post-worktime-logger#63]
Just wanted to add my dev setup as a PR (if you are interested).
it's a basic docker image and a docker-compose.yml which sets up a running Wordpress 4.6.1 with mysql backend (final setup steps are needed).

**Comment by selamanse** [comment]
PR #64 created

**Comment by blackus3r** [comment]
Nice idea! 
I will have a look at this. 
But we have to change the base of the pull request to swimlane/1.4.0.
